### ISSUE TITLE
Extra head-tail empty string in data batch

### ISSUE THREAD

**Issue by TomNong** [asyml/texar-pytorch#118]
Currently, in the PR #116, there is possible extra head-tail empty string("") in loading `ptb` data(train, valid and test), using `MonoTextData` and `TrainTestDataIterator`. 

E.g. https://github.com/asyml/texar-pytorch/blob/6e7d61f5faa38b6b8a7bfa04425d9277ecc6f7d0/examples/vae_text/vae_train.py#L135 here the correct `data_batch["text"]` could be `['<BOS>', 'abc', ...'cba', '<EOS>']`, but the actual data is `['<BOS>', '', 'abc', ...'cba', '', '<EOS>']`. Two empty strings are added between the head and tail, along with the `data_batch["text_ids"]`.

This issue is only found when loading the `ptb` data now.

**Comment by huzecong** [comment]
This is because the PTB dataset contains one leading space and one trailing space per line. In the `process` method of `MonoTextData`, each line is split on `hparams.delimiter`, which is now set to a space. This will produce empty strings when there are leading, trailing, or duplicate space characters.

A way to address this is to set the default delimiter to `None`. `str.split(None)` would split on any blank character and ignore duplicated blanks. Make sure to also document this behavior. @AvinashBukkittu can you do this?

BTW, the formatting in `MonoTextData.default_hparams` docstring also needs fixing.
