### ISSUE TITLE
embedding_fn of GPT2Decoder

### ISSUE THREAD

**Issue by ZhitingHu** [asyml/texar-pytorch#119]
[Here](https://github.com/asyml/texar-pytorch/tree/master/examples/gpt-2#other-use-cases), `_embedding_fn` should be defined inside `GPT2Decoder`. And in `Ex. Use 1)`, there is no need to specify `decoder(..., embedding=_embedding_fn)`

**Comment by ZhitingHu** [comment]
But in `Ex. Use 2)`, the helper will need an embedder. How would this work, since the GPT2Decoder already has embedders inside?

**Comment by gpengzhi** [comment]
For the first question, I think `embedding=_embedding_fn` is necessary. [Here](https://github.com/asyml/texar-pytorch/blob/master/texar/modules/decoders/decoder_base.py#L129), When `decoding_strategy == "infer_greedy"`, `embedding`, `start_tokens`, and `end_token` are required. `start_tokens` are computed [here](https://github.com/asyml/texar-pytorch/blob/master/texar/modules/decoders/transformer_decoders.py#L502).

**Comment by gpengzhi** [comment]
For the second question, we assigned `_embedding_fn` to `helper`. For example,

```python
helper = tx.modules.TopPSampleEmbeddingHelper(
                embedding=_embedding_fn,
                start_tokens=start_tokens,
                end_token=end_token,
                p=args.top_p,
                softmax_temperature=args.temperature)
```

**Comment by ZhitingHu** [comment]
So, in current implementation, The internal use of `GPT2Decoder`'s  embedders is only for `decoding_strategy='train_greedy'`?

**Comment by gpengzhi** [comment]
Yes. But we could include the embedding part if the input for the `GPT2Decoder` is `helper_type` instead of `helper`, and build the `helper` inside `GPT2Deocder`. I am not sure if this is a better interface though since all other `decoder` in `texar` requires `helper` instead of `helper_type`.

**Comment by huzecong** [comment]
I would still prefer using `helper` instead of `helper_type`. That reminds me, `XLNetDecoder` now takes `helper_type` and should be changed.

Helpers need access to embeddings because certain helpers (e.g. `SoftmaxEmbeddingHelper`) produces a weighted average of embeddings as the next input. But for a range of models, embeddings are part of the model and shouldn't/can't be separated and exposed to the user.

I think it might be better to rework the helper & decoder interfaces. How about this: we add a method in decoder called `embed_tokens`, which converts tokens to embeddings; we move the `embedding` argument from helper constructor to `next_inputs`, and pass `embed_tokens` as the value. This way, the user will not have to deal with the embeddings issue, it would be handled internally by the decoder. We can also make `embed_tokens` take two arguments `tokens` and `time`, so we don't need to check the number of arguments in helpers, which I think is a bit of a hack.

**Comment by ZhitingHu** [comment]
I agree that for decoders like `GPT2Decoder`, embedders should not be exposed to users since they are internal in the module.

For Zecong's suggestion, one potential issue is that, besides `next_inputs`, the `sample()` method of helper can also need embeddings. So, it looks necessary to pass embedders to the helper constructor.

At this point, for a quick adaption, I think we can simply allow the `helper` argument to be set to the name of the Helper, and the decoder constructs the helper internally. That is, `helper` can  be (1) an object already constructed (2) a Helper class (3) the name of the class. This is a common interface in Texar. E.g., many of the hparams fields allow the these options.

**Comment by huzecong** [comment]
I think we can allow `helper` to be a type, but then we would have to also accept helper kwargs as arguments, because certain helpers (e.g. `TopK`) require other arguments that cannot be supplied by the decoder.

I'm not sure what is the merit of having access to embeddings in `sample`, because none of the helpers that are currently implemented require embeddings in `sample`. Could you show me an example of the potential usage? Anyway, we can also add `embedding_fn` to sample, so the burden of implementation is still within the library, but not delegated to the user.
