### ISSUE TITLE
Support GPT-2 774M checkpoint file & Rename the current GPT2 checkpoint files

### ISSUE THREAD

**Issue by gpengzhi** [asyml/texar-pytorch#169]
https://github.com/openai/gpt-2

In their official website, `Note that our original parameter counts were wrong due to an error (in our previous blog posts and paper). Thus you may have seen small referred to as 117M and medium referred to as 345M.`

We should rename ours as well. `We have currently released small (124M parameter), medium (355M parameter), and large (774M parameter) versions of GPT-2.`

**Comment by ZhitingHu** [comment]
Ok.. We can probably use `small`, `medium`, `large`, and still keep support of `117M` and `345M` with a deprecation warning?

**Comment by gpengzhi** [comment]
Maybe we can directly replace `117M` and `345M` by `gpt2-small` and `gpt2-medium`?

**Comment by ZhitingHu** [comment]
Continuing to support `117M` and `345M` for a while could be good to avoid breaking users' code suddenly. But since texar-pytorch is not formally released yet, we can drop the support, but may want to add an explicit error msg when users specify "117M" as a name, telling them to use `gpt2-small` instead.
