### ISSUE TITLE
Can install texar-pytorch and texar-tensorflow

### ISSUE THREAD

**Issue by XinDongol** [asyml/texar-pytorch#212]
It seems that there is some conflict if we install `texar-pytorch` and `texar-tensorflow` in the same env. 
I got the same error as #130

**Comment by XinDongol** [comment]
If I install texar-tf first, I can not import `texar.torch` after installing texar-pytorch. 

However, after uninstalling texar-tf, everything is fine.

**Comment by huzecong** [comment]
Sorry, this is probably due to our installation instructions being out-of-date. Could you try installing both libraries using `pip install .` (without `-e`)?

**Comment by XinDongol** [comment]
works now. Thanks a lot.

**Comment by ha-lins** [comment]
I advise that the texar-tf and pytorch version should both support ` pip install . -e`.  Do you konw how to do that? Thanks! @huzecong

**Comment by huzecong** [comment]
@ha-lins Both versions work with `pip install . -e` when installed individually, but it will not be possible to install both packages at the same time with `-e`. This is because the folders `texar/tf/` and `texar/torch/` must have a shared parent folder `texar/`, and it is not possible to do so with `-e`.
