### ISSUE TITLE
Re-factor Examples to use the Executor API?

### ISSUE THREAD

**Issue by ankitvad** [asyml/texar-pytorch#307]
Why don't the simpler examples:
- Classifier
-VAE Text
-Seq2Seq+Attention

utilize the Executor API for training instead of the main() function and for-loops? There exists executor calls for the transformers. 

Does the executor not work for these applications?

**Comment by huzecong** [comment]
Thank you for your interest in Texar-PyTorch! The `vae_text`, `seq2seq_attn`, and `sentence_classifier` examples are definitely possible to implement with the Executor APIs. However, since Texar aims to be versatile and general purpose framework, we believe that it's also beneficial to demonstrate how to implement models using the usual training loops. This is also why we have several different versions of training scripts for examples like `bert`.

That said, if you're willing to contribute, you're more than welcome to create a pull request add your implementation of examples using the Executor API!
