### ISSUE TITLE
AttentionRNNDecoder param initial_state wrapped in AttentionWrapperState

### ISSUE THREAD

**Issue by TomNong** [asyml/texar-pytorch#54]
Hi @gpengzhi , we noticed that it would be too heavy to wrap the AttentionRNNDecoder forward method parameter "initial_state" into AttentionWrapperState. The position is here: https://github.com/asyml/texar-pytorch/blob/master/texar/modules/decoders/rnn_decoders.py#L518. Would you consider making it as a regular tensor? Thanks!

**Comment by gpengzhi** [comment]
Good point. @TomNong I think we could simplify this part. Let me think about the code refactoring on the part.

**Comment by huzecong** [comment]
In the TF version, the user only needs to provide the actual cell state (not the wrapper state) as `initial_state`, and the state is wrapped into an `AttentionWrapperState` in `AttentionRNNDecoder.initialize`. We could follow similar logic here.

Note that this breaks the type annotations in the method signature, as `initial_state` is no longer of type `Optional[State]` where `State` is the first type argument of `RNNDecoder`. Consider changing the annotation of `initial_state` to `Optional[RNNCellBase]` which allows arbitrary cell types. mypy should not report errors since the signature is already `# type: ignore`'d.
